"""
Export Utilities for Automaton Auditor Dashboard

Provides export functionality for:
- Markdown reports
- Text reports
- JSON reports
- Video demonstration scripts
- PDF reports (optional)
"""

import json
from datetime import datetime
from typing import Dict, List, Any, Optional
from pathlib import Path


def export_to_markdown(report, evidences: Dict, opinions: List) -> str:
    """
    Export audit results to Markdown format.
    
    Args:
        report: AuditReport object
        evidences: Dictionary of evidence from detectives
        opinions: List of JudicialOpinion objects
    
    Returns:
        Markdown-formatted string
    """
    md = []
    
    # Header
    md.append("# 🔍 Automaton Auditor Report")
    md.append("")
    md.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    md.append(f"**Repository:** {report.repo_url}")
    md.append(f"**Overall Score:** {report.overall_score:.1f}/5.0")
    md.append("")
    md.append("---")
    md.append("")
    
    # Executive Summary
    md.append("## 📝 Executive Summary")
    md.append("")
    md.append(report.executive_summary)
    md.append("")
    
    # Score Overview
    md.append("## 📊 Score Overview")
    md.append("")
    md.append("| Criterion | Score | Status |")
    md.append("|-----------|-------|--------|")
    
    grade_map = {5: "🟢 Excellent", 4: "🟢 Good", 3: "🟡 Satisfactory", 2: "🔴 Poor", 1: "🔴 Fail"}
    
    for criterion in report.criteria:
        status = grade_map.get(criterion.final_score, "Unknown")
        md.append(f"| {criterion.dimension_name} | {criterion.final_score}/5 | {status} |")
    
    md.append("")
    
    # Detailed Analysis
    md.append("## 📋 Detailed Analysis")
    md.append("")
    
    for criterion in report.criteria:
        md.append(f"### {criterion.dimension_name}")
        md.append("")
        
        # Score
        status = grade_map.get(criterion.final_score, "Unknown")
        md.append(f"**Score:** {criterion.final_score}/5 - {status}")
        md.append("")
        
        # Judge Opinions
        md.append("#### Judge Opinions")
        md.append("")
        
        for opinion in criterion.judge_opinions:
            judge_emoji = {"Prosecutor": "⚖️", "Defense": "🛡️", "TechLead": "👨‍💼"}
            emoji = judge_emoji.get(opinion.judge, "📋")
            md.append(f"**{emoji} {opinion.judge}:** {opinion.score}/5")
            md.append(f"_{opinion.argument}_")
            md.append("")
        
        # Dissent
        if criterion.dissent_summary:
            md.append("#### Dissent")
            md.append("")
            md.append(f"> {criterion.dissent_summary}")
            md.append("")
        
        # Remediation
        md.append("#### Remediation")
        md.append("")
        md.append(criterion.remediation)
        md.append("")
        md.append("---")
        md.append("")
    
    # Evidence Summary
    md.append("## 🔍 Evidence Summary")
    md.append("")
    
    for detective_name, evidence_list in evidences.items():
        if evidence_list:
            md.append(f"### {detective_name.replace('_', ' ').title()}")
            md.append("")
            
            for ev in evidence_list:
                found = "✅" if ev.found else "❌"
                md.append(f"- **{found} {ev.goal}** (Confidence: {ev.confidence:.0%})")
                md.append(f"  - {ev.rationale}")
                md.append("")
    
    # Remediation Plan
    md.append("## 🔧 Remediation Plan")
    md.append("")
    md.append(report.remediation_plan)
    md.append("")
    
    # Footer
    md.append("---")
    md.append("*Generated by Automaton Auditor - Digital Courtroom*")
    
    return "\n".join(md)


def export_to_text(report, evidences: Dict, opinions: List) -> str:
    """
    Export audit results to plain text format.
    
    Args:
        report: AuditReport object
        evidences: Dictionary of evidence from detectives
        opinions: List of JudicialOpinion objects
    
    Returns:
        Plain text string
    """
    lines = []
    
    # Header
    lines.append("=" * 60)
    lines.append("AUTOMATON AUDITOR REPORT")
    lines.append("=" * 60)
    lines.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"Repository: {report.repo_url}")
    lines.append(f"Overall Score: {report.overall_score:.1f}/5.0")
    lines.append("")
    
    # Executive Summary
    lines.append("EXECUTIVE SUMMARY")
    lines.append("-" * 40)
    lines.append(report.executive_summary)
    lines.append("")
    
    # Score Overview
    lines.append("SCORE OVERVIEW")
    lines.append("-" * 40)
    
    for criterion in report.criteria:
        lines.append(f"  {criterion.dimension_name}: {criterion.final_score}/5")
    
    lines.append("")
    
    # Detailed Analysis
    lines.append("DETAILED ANALYSIS")
    lines.append("-" * 40)
    
    for criterion in report.criteria:
        lines.append(f"\n{criterion.dimension_name}")
        lines.append(f"  Score: {criterion.final_score}/5")
        lines.append(f"  Remediation: {criterion.remediation}")
        
        if criterion.dissent_summary:
            lines.append(f"  Dissent: {criterion.dissent_summary}")
        
        lines.append("  Judge Opinions:")
        for opinion in criterion.judge_opinions:
            lines.append(f"    - {opinion.judge}: {opinion.score}/5 - {opinion.argument[:100]}...")
    
    # Evidence Summary
    lines.append("\nEVIDENCE SUMMARY")
    lines.append("-" * 40)
    
    for detective_name, evidence_list in evidences.items():
        if evidence_list:
            lines.append(f"\n{detective_name.replace('_', ' ').title()}:")
            for ev in evidence_list:
                found = "YES" if ev.found else "NO"
                lines.append(f"  [{found}] {ev.goal} - {ev.rationale[:80]}")
    
    # Remediation Plan
    lines.append("\nREMEDIATION PLAN")
    lines.append("-" * 40)
    lines.append(report.remediation_plan)
    lines.append("")
    
    # Footer
    lines.append("=" * 60)
    lines.append("Generated by Automaton Auditor")
    lines.append("=" * 60)
    
    return "\n".join(lines)


def export_to_json(report, evidences: Dict, opinions: List) -> str:
    """
    Export audit results to JSON format.
    
    Args:
        report: AuditReport object
        evidences: Dictionary of evidence from detectives
        opinions: List of JudicialOpinion objects
    
    Returns:
        JSON string
    """
    # Convert to dict
    data = {
        "metadata": {
            "generated_at": datetime.now().isoformat(),
            "repo_url": report.repo_url,
            "overall_score": report.overall_score
        },
        "report": report.model_dump() if hasattr(report, 'model_dump') else report.dict(),
        "evidences": {
            detective: [ev.model_dump() if hasattr(ev, 'model_dump') else ev.dict() 
                       for ev in evidence_list]
            for detective, evidence_list in evidences.items()
        },
        "opinions": [op.model_dump() if hasattr(op, 'model_dump') else op.dict() 
                    for op in opinions]
    }
    
    return json.dumps(data, indent=2)


def generate_video_script(report, evidences: Dict, opinions: List) -> str:
    """
    Generate a video demonstration script.
    
    Args:
        report: AuditReport object
        evidences: Dictionary of evidence from detectives
        opinions: List of JudicialOpinion objects
    
    Returns:
        Video script as string
    """
    script = []
    
    script.append("""
================================================================================
AUTOMATON AUDITOR - VIDEO DEMONSTRATION SCRIPT
================================================================================

[INTRO - 0:00 - 0:15]
---
Title: "Automaton Auditor - Digital Courtroom for Code Quality"

Welcome to this demonstration of the Automaton Auditor, a hierarchical 
multi-agent system that automatically audits GitHub repositories using 
a "Digital Courtroom" architecture.

[OVERVIEW - 0:15 - 0:45]
---
""")

    script.append(f"Today we're auditing: {report.repo_url}")
    script.append(f"Overall Score: {report.overall_score:.1f}/5.0 - {report.executive_summary[:200]}...")

    script.append("""

[SYSTEM ARCHITECTURE - 0:45 - 1:30]
---
The system consists of three layers:

1. DETECTIVE LAYER (Parallel Execution)
   - RepoInvestigator: Analyzes code structure, git history
   - DocAnalyst: Verifies report accuracy
   - VisionInspector: Analyzes architectural diagrams

2. JUDICIAL LAYER (Parallel Deliberation)
   - Prosecutor: Critical lens (finds flaws)
   - Defense: Optimistic lens (rewards effort)
   - TechLead: Pragmatic lens (architecture focus)

3. CHIEF JUSTICE (Synthesis)
   - Deterministic rule-based verdict generation
""")

    script.append("""
[EVIDENCE COLLECTION - 1:30 - 2:30]
---
""")

    for detective_name, evidence_list in evidences.items():
        script.append(f"\n{detective_name.replace('_', ' ').title()}:")
        for ev in evidence_list:
            status = "FOUND" if ev.found else "NOT FOUND"
            script.append(f"  - [{status}] {ev.goal}: {ev.rationale[:80]}")

    script.append("""

[JUDGE DELIBERATIONS - 2:30 - 3:30]
---
""")

    criteria = set(op.criterion_id for op in opinions)
    for criterion_id in criteria:
        criterion_opinions = [op for op in opinions if op.criterion_id == criterion_id]
        script.append(f"\n{criterion_id.replace('_', ' ').title()}:")
        
        for opinion in criterion_opinions:
            script.append(f"  {opinion.judge}: Score {opinion.score}/5")
            script.append(f"    \"{opinion.argument[:150]}...\"")

    script.append("""

[FINAL VERDICT - 3:30 - 4:15]
---
""")

    for criterion in report.criteria:
        script.append(f"\n{criterion.dimension_name}: {criterion.final_score}/5")
        if criterion.dissent_summary:
            script.append(f"  Dissent: {criterion.dissent_summary}")

    script.append(f"""
[REMEDIATION - 4:15 - 4:45]
---
{report.remediation_plan}

[OUTRO - 4:45 - 5:00]
---
Thank you for watching this demonstration of the Automaton Auditor!

For more information, visit the GitHub repository.

================================================================================
END OF SCRIPT
================================================================================
""")

    return "\n".join(script)


def generate_html_report(report, evidences: Dict, opinions: List) -> str:
    """
    Export audit results to HTML format.
    
    Args:
        report: AuditReport object
        evidences: Dictionary of evidence from detectives
        opinions: List of JudicialOpinion objects
    
    Returns:
        HTML-formatted string
    """
    import html
    from datetime import datetime
    
    html_content = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Automaton Auditor Report - {report.repo_url}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background: #f5f5f5;
        }}
        .header {{
            background: linear-gradient(135deg, #1e3a8a, #3b82f6);
            color: white;
            padding: 30px;
            border-radius: 12px;
            margin-bottom: 20px;
        }}
        .score-card {{
            display: inline-block;
            background: rgba(255,255,255,0.2);
            padding: 15px 30px;
            border-radius: 8px;
            margin: 10px 5px;
        }}
        .section {{
            background: white;
            padding: 20px;
            border-radius: 12px;
            margin-bottom: 20px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        .criterion {{
            border-left: 4px solid #3b82f6;
            padding: 15px;
            margin: 15px 0;
            background: #f8fafc;
        }}
        .score-5 {{ background: #dcfce7; color: #166534; }}
        .score-4 {{ background: #dcfce7; color: #166534; }}
        .score-3 {{ background: #fef9c3; color: #854d0e; }}
        .score-2 {{ background: #ffedd5; color: #9a3412; }}
        .score-1 {{ background: #fee2e2; color: #991b1b; }}
        .judge {{
            padding: 10px;
            margin: 5px 0;
            border-radius: 6px;
        }}
        .judge-prosecutor {{ background: #fef2f2; border-left: 3px solid #ef4444; }}
        .judge-defense {{ background: #eff6ff; border-left: 3px solid #3b82f6; }}
        .judge-techlead {{ background: #faf5ff; border-left: 3px solid #a855f7; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>⚖️ Automaton Auditor Report</h1>
        <p><strong>Repository:</strong> {html.escape(report.repo_url)}</p>
        <p><strong>Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        <div class="score-card">
            <h2>Overall Score: {report.overall_score:.1f}/5.0</h2>
        </div>
    </div>
    
    <div class="section">
        <h2>📝 Executive Summary</h2>
        <p>{html.escape(report.executive_summary)}</p>
    </div>
    
    <div class="section">
        <h2>📊 Score Breakdown</h2>
"""
    
    for criterion in report.criteria:
        score_class = f"score-{criterion.final_score}"
        html_content += f"""
        <div class="criterion">
            <h3>{html.escape(criterion.dimension_name)} <span class="{score_class}">{criterion.final_score}/5</span></h3>
            <p><strong>Remediation:</strong> {html.escape(criterion.remediation)}</p>
"""
        
        for opinion in criterion.judge_opinions:
            judge_class = f"judge-{opinion.judge.lower()}"
            html_content += f"""
            <div class="judge {judge_class}">
                <strong>{opinion.judge}:</strong> {opinion.score}/5
                <br><em>{html.escape(opinion.argument)}</em>
            </div>
"""
        
        if criterion.dissent_summary:
            html_content += f"<p><strong>Dissent:</strong> {html.escape(criterion.dissent_summary)}</p>"
        
        html_content += "</div>"
    
    html_content += f"""
    <div class="section">
        <h2>🔧 Remediation Plan</h2>
        <pre>{html.escape(report.remediation_plan)}</pre>
    </div>
    
    <footer style="text-align: center; padding: 20px; color: #666;">
        <p>Generated by Automaton Auditor - Digital Courtroom</p>
    </footer>
</body>
</html>
"""
    
    return html_content


# Alias for backwards compatibility
export_to_html = generate_html_report


def save_export(formats: List[str], output_dir: str, report, evidences, opinions) -> Dict[str, str]:
    """
    Save exports in multiple formats.
    
    Args:
        formats: List of formats ('markdown', 'text', 'json', 'html', 'video')
        output_dir: Directory to save files
        report: AuditReport object
        evidences: Dictionary of evidence
        opinions: List of opinions
    
    Returns:
        Dict mapping format to file path
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    repo_name = report.repo_url.split('/')[-1].replace('.git', '')
    
    saved = {}
    
    if 'markdown' in formats:
        md_file = output_path / f"audit_report_{repo_name}_{timestamp}.md"
        md_file.write_text(export_to_markdown(report, evidences, opinions), encoding='utf-8')
        saved['markdown'] = str(md_file)
    
    if 'text' in formats:
        txt_file = output_path / f"audit_report_{repo_name}_{timestamp}.txt"
        txt_file.write_text(export_to_text(report, evidences, opinions), encoding='utf-8')
        saved['text'] = str(txt_file)
    
    if 'json' in formats:
        json_file = output_path / f"audit_report_{repo_name}_{timestamp}.json"
        json_file.write_text(export_to_json(report, evidences, opinions), encoding='utf-8')
        saved['json'] = str(json_file)
    
    if 'html' in formats:
        html_file = output_path / f"audit_report_{repo_name}_{timestamp}.html"
        html_file.write_text(export_to_html(report, evidences, opinions), encoding='utf-8')
        saved['html'] = str(html_file)
    
    if 'video' in formats:
        video_file = output_path / f"video_script_{repo_name}_{timestamp}.txt"
        video_file.write_text(generate_video_script(report, evidences, opinions), encoding='utf-8')
        saved['video'] = str(video_file)
    
    return saved
